version: '2'
services:
  web:
    build:
      context: .
      args:
        VERSION: "${VERSION}"
    ports:
      - "8888:8888"
    depends_on:
     - postgres
    entrypoint: ./wait-for-postgres.sh postgres /app/bin/dotcom foreground

  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
